<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use jeremykenedy\LaravelRoles\App\Exceptions\RoleDeniedException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Throwable;
use App\Traits\ApiResponseTrait;

class Handler extends ExceptionHandler
{
    use ApiResponseTrait;
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $model = $e->getModel();
            $className = last(explode('\\', $model));
            return $this->error($className.' record not found.',404);
        }
        if ($e instanceof RoleDeniedException) {
            $message = $e->getMessage();
            return $this->error($message,403);
        }
        if ($e instanceof HttpException) {
            $message = $e->getMessage();
            return $this->error($message,403);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
